PROG=	l2_bridge_loader
SRCS=	l2_bridge_loader.c
OBJS=	${SRCS:.c=.o}
EBPFSRCS=	l2_bridge.bpf.c
EBPFOBJS=	${EBPFSRCS:.c=.o}
CFLAGS+=	\
	-O3 \
	-I ${BASE}/sys \
	-Wall
LIBS+= \
	-lgbpf \
	-lelf \

all: ${PROG} ${EBPFOBJS}

${EBPFOBJS}: ${EBPFSRCS}
	clang $(CFLAGS) -target bpf -c l2_bridge.bpf.c

${PROG}: ${OBJS}
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(LIBS)
CLEANFILES+=	${PROG} ${OBJS} ${EBPFOBJS}

install:
